services:
    recaptcha:
        class: Recaptcher\Recaptcha
        arguments: [%recaptcha_public_key%, %recaptcha_private_key%]

    form.type.recaptcha:
        class: Dmishh\Bundle\RecaptchaBundle\Form\Type\RecaptchaType
        arguments: [@recaptcha]
        tags:
            - { name: form.type, alias: recaptcha }

    form.validator.recaptcha:
        class: Dmishh\Bundle\RecaptchaBundle\Validator\Constraints\RecaptchaValidator
        scope: request
        arguments: [@recaptcha, @request]
        tags:
            - { name: validator.constraint_validator, alias: recaptcha }
